package com.emart.controller;

import java.util.List;

import org.json.simple.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.emart.accessData.User;
import com.emart.service.EmartService;
import com.emart.utils.Constants;

@RestController
public class EmartController {
	
//	@Autowired // This means to get the bean called userRepository Which is auto-generated by Spring, we will use it to handle the data
//	private UserRepository userRepository;
//	
	@Autowired
	private EmartService emartService;
	
	@PostMapping(path="/register")
	public ResponseEntity<JSONObject> registerUser(@RequestBody User user) {
		JSONObject response = emartService.register(user);	
		return new ResponseEntity<JSONObject>(response, HttpStatus.OK);
	}
	
	@PostMapping(path="/login")
	public ResponseEntity<JSONObject> loginuser(@RequestBody JSONObject loginDetails) {
		
		String username = (String) loginDetails.get("username");
		String password = (String)loginDetails.get("password");		
		JSONObject response = emartService.login(username, password);		
		return new ResponseEntity<JSONObject>(response, HttpStatus.OK);
	}
	
	@GetMapping(path="/getCategories")
	public ResponseEntity<JSONObject> getCategories(@RequestParam String username) {
		
		JSONObject response = emartService.getCategories();		
		return new ResponseEntity<JSONObject>(response, HttpStatus.OK);
	}

}
